.TH "TestAVLString" 3 "Fri Nov 7 2014" "AVLString" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestAVLString \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void TestAVLString\&.main (Stringargs[])\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for AVLString from the source code\&.
